### ISSUE TITLE
貌似这样成功率高点

### ISSUE THREAD

**Issue by andrewzjut** [dxhuii/delWeibo#4]
if($('a[action-type="fl_menu"]')) {
                            $('a[action-type="fl_menu"]').click();
                            if($('a[action-type="fl_del_fast_reported"]')){
                                $('a[action-type="fl_del_fast_reported"]').click();
                            }
                            if($('a[action-type="feed_list_delete"]')){
                                 $('a[action-type="feed_list_delete"]').click();
                                 $('a[action-type="ok"]').click();
                            }
                            if($('a[action-type="feed_list_delete_fast_reported"]')){
                                $('a[action-type="feed_list_delete_fast_reported"]').click();
                            }
                            if($('a[title="取消快转"]')){
                                $('a[title="取消快转"]').click();
                            }
                            if($('a[action-type="ok"]')){
                                $('a[action-type="ok"]').click();
                            }
                        }

**Comment by dxhuii** [comment]
已更新，有需要可以再试试
