### ISSUE TITLE
右侧的开始按钮建议搞大点，我琢磨了十来分钟，才发现这个按钮！

### ISSUE THREAD

**Issue by zhudashi** [dxhuii/delWeibo#7]
我是4k分辨率的显示器……真是看了很久才发现那个按钮，太隐蔽了。建议搞大，高亮。

**Comment by dxhuii** [comment]
好。最近两天处理下，我当时觉得太明显不太好，就随便弄下，很早之前是打开对应的页面直接删除的，后面才加了这个按钮。

**Comment by dxhuii** [comment]
![image](https://user-images.githubusercontent.com/2328917/201660846-c960212a-c260-4b84-a816-814c253fa685.png)


> 我是4k分辨率的显示器……真是看了很久才发现那个按钮，太隐蔽了。建议搞大，高亮。

已经修改了样式。
