### ISSUE TITLE
原博已经被删除，或者不可见等不展示的快转的微博，删不了，如图。

### ISSUE THREAD

**Issue by zhudashi** [dxhuii/delWeibo#8]
![微信截图_20221114111918](https://user-images.githubusercontent.com/47840178/201568102-c19b4616-27f9-4dba-b780-490f73262cad.png)
这种不能自动删除

**Comment by dxhuii** [comment]
我没有这样的数据，可以把这部分代码截图发一下。右击审查元素看下。我到时候尝试加一下。

**Comment by zhudashi** [comment]
这个问题我在你的基础上加了几行代码，现在跑了一下午，运行的很舒服。我倒是没太仔细研究啊，瞎改了改，反正能跑就行了。

添加在  **if (url.indexOf("//weibo.com/u/") !== -1) {**  的后面

```
  if( $('.vue-recycle-scroller__item-view .deletedToolbar_toolbarFull_1dOfW span')){
                   $('.deletedToolbar_toolbarFull_1dOfW span').click()
                   $('.vue-recycle-scroller__item-view .deletedToolbar_toolbarFull_1dOfW').remove()
  }
  else 
```
![微信截图_20221114174859](https://user-images.githubusercontent.com/47840178/201628756-90df9a9f-e4a2-49f3-b7c1-4afe57bcaf25.png)

我现在也没有这种情况的案例了，几万条微博删到18年的了，可能18年还没有快转功能……

说明一下：
**$('.deletedToolbar_toolbarFull_1dOfW span')**   是这个“取消快转”按钮
后面那个remove是点击按钮之后用来删除这个dom的，因为**在我的电脑上，点击这个按钮之后dom元素不会消失**，但实际上删除接口已经触发了，所以这里添加了一个remove。

**Comment by dxhuii** [comment]
> 这个问题我在你的基础上加了几行代码，现在跑了一下午，运行的很舒服。我倒是没太仔细研究啊，瞎改了改，反正能跑就行了。
> 
> 添加在 **if (url.indexOf("//weibo.com/u/") !== -1) {** 的后面
> 
> ```
>   if( $('.vue-recycle-scroller__item-view .deletedToolbar_toolbarFull_1dOfW span')){
>                    $('.deletedToolbar_toolbarFull_1dOfW span').click()
>                    $('.vue-recycle-scroller__item-view .deletedToolbar_toolbarFull_1dOfW').remove()
>   }
>   else 
> ```
> 
> ![微信截图_20221114174859](https://user-images.githubusercontent.com/47840178/201628756-90df9a9f-e4a2-49f3-b7c1-4afe57bcaf25.png)
> 
> 我现在也没有这种情况的案例了，几万条微博删到18年的了，可能18年还没有快转功能……
> 
> 说明一下： **$('.deletedToolbar_toolbarFull_1dOfW span')** 是这个“取消快转”按钮 后面那个remove是点击按钮之后用来删除这个dom的，因为**在我的电脑上，点击这个按钮之后dom元素不会消失**，但实际上删除接口已经触发了，所以这里添加了一个remove。

已经合并到代码里面了，感谢提供
